#!/bin/bash

KEY_SIZE=1024
VAL_SIZE=1048576

key=$(ssh wangzh@warmcode.net "head -c ${KEY_SIZE} /dev/urandom | base64 | head -c ${KEY_SIZE}")
value=$(ssh wangzh@warmcode.net "head -c ${VAL_SIZE} /dev/urandom | base64 | head -c ${VAL_SIZE}")

echo ${key} > key.txt
echo ${value} > value.txt


