#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_MAIN                                100
#define IDD_ABOUT                               108
#define ID_MAIN                                 109
#define IDB_TOOLBAR_MAIN                        110
#define IDD_HARDWARE                            111
#define IDD_FONT                                112
#define IDD_COLOR                               113
#define IDD_GOTOLINE                            114
#define IDD_PHER                                117
#define IDD_BREAKPOINT                          118
#define IDC_LIST1                               1002
#define IDC_BUTTON1                             1003
#define IDC_LST_COLORS                          1005
#define IDC_ADDRESS                             1006
#define IDC_BTN_OK                              1007
#define IDC_EDIT3                               1013
#define IDC_EDIT4                               1014
#define IDC_EDIT1                               1015
#define IDC_BRKVALUE                            1016
#define IDC_EDIT2                               1016
#define IDC_EDIT5                               1017
#define IDC_EDIT6                               1018
#define IDM_EXIT                                4002
#define IDM_HELP                                4003
#define IDM_ABOUT                               4004
#define IDC_RS                                  4005
#define IDM_FILE_OPEN                           4007
#define IDM_FILE_DUMP                           4008
#define IDM_PROTOCAL_DEBUG                      4009
#define IDA_RUN                                 4014
#define IDM_EXE_RUN                             4014
#define IDM_VIEW_FONT                           4015
#define IDM_VIEW_COLOR                          4016
#define IDM_VIEW_FULLSCREEN                     4018
#define IDM_VIEW_GOTOLINE                       4019
#define IDM_FILE_CLOSE                          4020
#define IDM_VIEW_TOOLBAR                        4021
#define IDM_FILE_SAVESOURCE                     4022
#define IDM_EMU_SETBREAK                        4023
#define ID_MENUITEM4024                         4024
#define IDM_STAY                                4027
#define ID_MENUITEM4028                         4028
#define IDM_EXE_BRK                             4030
#define IDB_CHIP                                5031
#define IDD_PROTOCAL_DEBUG                      10000
#define IDC_OUTDUMP                             10001
#define IDC_MSGSEND                             10002
#define IDM_DEBUG                               10006
#define IDM_CONNECT                             10007
#define IDM_DISCONNECT                          10008
#define ID_COLOR_SPLITBAR                       40000
#define ID_COLOR_CURLINE                        40001
#define IDS_DATAVIEW                            40002
#define IDS_CODEVIEW                            40003
#define IDS_REGVIEW                             40004
#define IDS_STACKVIEW                           40005
